### ISSUE TITLE
The package with binary files has the wrong folder name for Apple OS.

### ISSUE THREAD

**Issue by ALIENQuake** [Argent77/tileconv#2]
The zip package with binary files (http://www.shsforums.net/files/file/1094-tileconv-a-mostis-compressor/) files has the wrong folder name for Apple OS:
![image](https://user-images.githubusercontent.com/365255/236674008-24515c6e-a2d2-4153-90cc-572076114147.png)

According to the docs, the folder name should be called `osx` for Apple OS.

Not a big deal but easy to fix for next release.

**Comment by Argent77** [comment]
Yeah, the chosen name for that folder isn't perfect. The binary package for [tile2ee](https://github.com/InfinityTools/tile2ee) has the same issue. I'll create a repackaged version eventually.

**Comment by ALIENQuake** [comment]
Just to clarify, by 'documentation' I mean this one: https://github.com/InfinityTools/tileconv/blob/master/tileconv/WeiDU/example_tileconv.txt#L21
I'm aware that the newest name for Apple Desktop OS is "macOS" but I'm not sure if changing it into this one for 2 tools would be beneficial without changing it for every common used WeiDU functions.

**Comment by ALIENQuake** [comment]
@Argent77 SHSForums.net has been down for many months, can you please add packages with compiled binary files?

**Comment by Argent77** [comment]
> Yeah, the chosen name for that folder isn't perfect. The binary package for [tile2ee](https://github.com/InfinityTools/tile2ee) has the same issue. I'll create a repackaged version eventually.

I totally forgot about this issue. I'll fix it asap.

> @Argent77 SHSForums.net has been down for many months, can you please add packages with compiled binary files?

Yes, will do.

**Comment by Argent77** [comment]
Resolved: https://github.com/InfinityTools/tileconv/releases/tag/v0.6.1
